extraArgs:
  provider: oidc
  oidc-issuer-url: http://ad904c01c5cc9475e85a33e79fb7085a-843788484.eu-west-1.elb.amazonaws.com/realms/flask-app
  client-id: flask-app
  client-secret: $(OAUTH2_PROXY_CLIENT_SECRET)
  redirect-url: http://ad904c01c5cc9475e85a33e79fb7085a-843788484.eu-west-1.elb.amazonaws.com/oauth2/callback
  scope: "openid email profile"
  standard-logging: true
  request-logging: true
  auth-logging: true

config:
  emailDomains:
    - "*"
  cookieSecret: $(OAUTH2_PROXY_COOKIE_SECRET)
  cookieSecure: false

service:
  portNumber: 4180

ingress:
  enabled: true
  className: alb
  path: /oauth2
  pathType: Prefix
  annotations:
    "alb.ingress.kubernetes.io/actions.ssl-redirect.type": "redirect"
    "alb.ingress.kubernetes.io/certificate-arn": "arn:aws:acm:eu-west-1:297071026656:certificate/b368021d-cc49-44b0-b471-c4f63b1d6d29"
    "alb.ingress.kubernetes.io/group.name": "datavisyn-test-eks"
    "alb.ingress.kubernetes.io/healthcheck-protocol": "HTTP"
    "alb.ingress.kubernetes.io/listen-ports": '[{"HTTP":80},{"HTTPS":443}]'
    "alb.ingress.kubernetes.io/scheme": "internet-facing"
    "alb.ingress.kubernetes.io/security-groups": "sg-0a40c3fb9984685c7,sg-0835829910c38d499"
    "alb.ingress.kubernetes.io/ssl-redirect": "443"
    "alb.ingress.kubernetes.io/subnets": "subnet-069367606b8060556,subnet-04c8dd2c131b4ffdc,subnet-04b2c5c5a86c07bda"
    "alb.ingress.kubernetes.io/target-type": "ip"
  hosts:
    - oauth.datavisyn.pro

extraEnv:
  - name: OAUTH2_PROXY_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth2-proxy-secret
        key: client-secret
  - name: OAUTH2_PROXY_COOKIE_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth2-proxy-secret
        key: cookie-secret
