replicaCount: 1

image:
  repository: abanoub65709/flask-app
  tag: v1.0.1
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # runAsUser: 1000
  # runAsGroup: 3000
  # fsGroup: 2000

service:
  type: nodePort
  port: 5000

ingress:
  enabled: true
  className: "alb"
  annotations: 
    "alb.ingress.kubernetes.io/actions.ssl-redirect.type": "redirect"
    "alb.ingress.kubernetes.io/certificate-arn": "arn:aws:acm:eu-west-1:297071026656:certificate/b368021d-cc49-44b0-b471-c4f63b1d6d29"
    "alb.ingress.kubernetes.io/group.name": "datavisyn-test-eks"
    "alb.ingress.kubernetes.io/healthcheck-protocol": "HTTP"
    "alb.ingress.kubernetes.io/listen-ports": '[{"HTTP":80},{"HTTPS":443}]'
    "alb.ingress.kubernetes.io/scheme": "internet-facing"
    "alb.ingress.kubernetes.io/security-groups": "sg-0a40c3fb9984685c7,sg-0835829910c38d499"
    "alb.ingress.kubernetes.io/ssl-redirect": "443"
    "alb.ingress.kubernetes.io/subnets": "subnet-069367606b8060556,subnet-04c8dd2c131b4ffdc,subnet-0af61a14ee5b627d4"
    "alb.ingress.kubernetes.io/target-type": "ip"
  hosts:
    - host: app.datavisyn.pro
      paths:
        - path: /
          pathType: prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

